""" System Varaibes to be used with non test


"""
IMGPATH = ''
FACE_DETECTION_MODULE = ''
NEWFACE = ''
ROOTCAPATH = ''
PRIVATEKEYPATH = ''
CERTIFICATEPATH = ''
HOST = ''
DEVICENAME = ''
FACE_COLLECTION_ID = ''
COLLECTION_CREATED = ''
PATH_TO_USERS = ' .json'

